### ISSUE TITLE
Calculate Upload/Donwload speed during testing

### ISSUE THREAD

**Issue by VerachadW** [akinaru/speed-test-lib#1]
First of all, your library is pretty amazing and easy to use. Thanks for that. Still, I want to show the speed of download and upload during testing. I already done on the download part but I can't figure out how to do on the upload part. Do you have any idea how to work on that?

**Comment by akinaru** [comment]
Thank you for your feedback, I've added following api in 1.03 :
```
SpeedTestReport getLiveDownloadReport()
```
and 
```
SpeedTestReport getLiveUploadReport()
```
Class `SpeedTestReport` contain information you need to monitor your download/upload :
* progress in %
* transfer rate in bps
* transfer rate in Bps
* speed test mode (UPLOAD or DOWNLOAD)
* total packet size to upload/download
* current packet size already uploaded/downloaded
* start time of download/upload
* current time (date of this measurement)

The following example will request download/upload report each second 

```
Timer timer = new Timer();

TimerTask task = new TimerTask() {

    @Override
    public void run() {

        if (speedTestSocket.getSpeedTestMode() == SpeedTestMode.UPLOAD) {

            SpeedTestReport uploadReport = speedTestSocket.getLiveUploadReport();
            System.out.println("---------------current upload report--------------------");
            System.out.println("progress             : " + uploadReport.getProgressPercent() + "%");
            System.out.println("transfer rate bit    : " + uploadReport.getTransferRateBit() + "b/s");
            System.out.println("transfer rate octet  : " + uploadReport.getTransferRateOctet() + "B/s");
            System.out.println("uploaded for now     : " + uploadReport.getTemporaryPacketSize() 
                                    + "/" + uploadReport.getTotalPacketSize());
            System.out.println("amount of time       : " + 
                                ((uploadReport.getReportTime() - uploadReport.getStartTime()) / 1000) + "s");
            System.out.println("--------------------------------------------------------");

        } else if (speedTestSocket.getSpeedTestMode() == SpeedTestMode.DOWNLOAD) {

            SpeedTestReport downloadReport = speedTestSocket.getLiveDownloadReport();
            System.out.println("---------------current download report--------------------");
            System.out.println("progress             : " + downloadReport.getProgressPercent() + "%");
            System.out.println("transfer rate bit    : " + downloadReport.getTransferRateBit() + "b/s");
            System.out.println("transfer rate octet  : " + downloadReport.getTransferRateOctet() + "B/s");
            System.out.println("downloaded for now   : " + downloadReport.getTemporaryPacketSize() 
                                    + "/" + downloadReport.getTotalPacketSize());
            System.out.println("amount of time       : "
                                    + ((downloadReport.getReportTime() - downloadReport.getStartTime()) / 1000) + "s");
        }
    }
};

// scheduling the task at interval
timer.scheduleAtFixedRate(task, 0, 1000);
```

**Comment by VerachadW** [comment]
Should we generate report and send it as a parameter for `onDownloadProgress` and `onUploadProgress` instead? So, it easier to get the report. Another suggestion is I think `percent` should be `float` since the precision will be lost if we test with a large file. BTW, I love the report idea. :+1:

**Comment by akinaru** [comment]
Yes it would be good to have values in `onDownloadProgress()` and `onUploadProgress()` too. I've added `getLiveUploadReport()` and `getLiveDownloadReport()` in case you want to request values with a fixed interval of your own. I will change percent format to `float`. Thank you for your feedback

**Comment by akinaru** [comment]
I've changed the API as following in 1.04 :
```
void onDownloadProgress(float percent,SpeedTestReport downloadReport) 
void onUploadProgress(float percent,SpeedTestReport uploadReport)
```
But for now, I manage differently upload & download progress : 
* Upload will divide data to upload in 100 chunks and will dispatch each chunk one by one. Hence, `onUploadProgress` will only be called one % at a time.
* For download, I dispatch `onDownloadProgress` each time some data is read from the socket (max 65535 octet at a time but in practice, often 1448 octet depending on the test server/connection etc..). 

So download progress in % isn't likely to have incremental value whereas upload progress will for sure.
I'm opened to any suggestion
For instance, for upload, we could parameter chunk number uploaded at one time, to match specific progress step (for instance 200 chunks will give 0.5% step)

**Comment by VerachadW** [comment]
Just try it and work like a charm. For the chunk parameter, I think it would be nice to be able to change the step of uploading progress. Many thanks for the quick responses.

**Comment by VerachadW** [comment]
After implement and test several times, I think chunk parameter should be used for both download and upload testing. This will give the same progress step when rendering the UI.

**Comment by akinaru** [comment]
I've changed the behavior, now we don't set the progress step of upload but the size of each packet sent to server which would give something closer to download progress if we set it to TCP packet size (which vary of course but limited < 65535 octet in theory)
I've set the default chunk size to 65535 and add `void setUploadChunkSize(int chunkSize)` and `int getUploadChunkSize()` APIs to set/get the size of each packet uploaded to server which would influence the step.
With the default (65535 octet), upload progress step should be similar to download progress step (for download : reading at most 65535 octet / for uploading writing exactly 65535 octet)
