### ISSUE TITLE
INVALID_HTTP_RESPONSE on onUploadCompleted

### ISSUE THREAD

**Issue by tiwiz** [akinaru/speed-test-lib#13]
Upon UploadCompleted, with latest version 1.21 (the only thing changed was the version, from 1.16 to 1.21) the `onUploadError` gets called with the following data instead on `onUploadCompleted`

<img width="606" alt="screen shot 2016-10-10 at 14 02 26" src="https://cloud.githubusercontent.com/assets/2534841/19235535/8131456c-8ef2-11e6-87dc-32f90f2c41d3.png">

The upload, though, looks good.

We are trying to upload to the following location: 52.18.71.122/tools/test_upload.dat (with version 1.16 it was working as intended)

**Comment by akinaru** [comment]
Yes it was working before, because I didn't check the status code for download & upload. It makes sense that your `POST /tools/test_upload.dat` should return `200 OK` instead of `404 Not Found`. Do you have any reason to get a `404` ?

**Comment by tiwiz** [comment]
No idea, honestly. 

Is there any check on my side I can do in order to help?

**Comment by akinaru** [comment]
To workaround your issue, I've set up a temporary repo 
```
compile 'com.github.akinaru:speedtest-tmp:1.21'
```
with my user repo 
```
maven {
    url 'http://dl.bintray.com/akinaru/maven'
}   
```

with a version dropping the check but you should fix the `404` issue on the server side (if you have access to it) and get back to the original repository

**Comment by tiwiz** [comment]
Thanks!

I will ask to check the server guys and get back to you!

Thanks again!
