### ISSUE TITLE
Cannot resolve symbol HttpFrame

### ISSUE THREAD

**Issue by mvauclare** [akinaru/speed-test-lib#15]
Hello,

I try to use this library in an android studio project.

When I try to compile for a run on my test tablet, I have an error : 
in file : SpeedTestTask.java
on line : final HttpFrame httpFrame = new HttpFrame();

HttpFrame seems to doesn't exist.

Is there anything to import before ?

Thank you,

**Comment by mvauclare** [comment]
I reply to my question : 

As it was perfectly explained in the readme http-endec external library is necessary to run (https://github.com/akinaru/http-endec)

**Comment by akinaru** [comment]
Hello,

The recommended way would be to integrate with Gradle or Maven if you can afford it : http://search.maven.org/#artifactdetails%7Ccom.github.akinaru%7Cspeedtest%7C1.23%7C
This way, it's much easier to deal with dependencies and to update the library version in case you want to try a higher version
