### ISSUE TITLE
Setting timeout

### ISSUE THREAD

**Issue by chandra-kantha** [akinaru/speed-test-lib#2]
Thanks for such a nice library.  Can you add one more parameter for time out. Lets say user is in very low network, I dont want keep the user in the screen for a long time. I just want an option like if the download is not complete in one minute, Just stop speed test process.

**Comment by akinaru** [comment]
Thank you for your feedback. I added in version 1.07, a socket timeout value in milliseconds you can pass it as argument in `SpeedTestSocket` constructor.

The following define a socket timeout of 5 seconds : 
```
SpeedTestSocket speedTestSocket = new SpeedTestSocket(5000);
```
This will trigger a `onDownloadError` or `onUploadError` callback and stop tasks when socket communication timeout

To get version 1.07 : 
```
compile 'com.github.akinaru:speedtest:1.07'
```

**Comment by akinaru** [comment]
I changed the API in 1.09 to : 
```
speedTestSocket.setSocketTimeout(5000);
```

This timeout only apply for download (socket read). I will soon add a fix to make it work for upload too

**Comment by chandra-kantha** [comment]
Okay, Thats great.
Thank you.

**Comment by akinaru** [comment]
Upload timeout was fixed in `v1.11` : https://github.com/akinaru/speed-test-lib/commit/43a24c800b9c6476599f358b148d4da4fa09fd9e
Default value for both download/upload is set to 10s
Let me know if you have any issue

**Comment by chandra-kantha** [comment]
Okay, Thank you so much. Sure, I will let you know if i find any issues.

**Comment by chandra-kantha** [comment]
Hello,

 Is 1.testdebit.info down? I'm not able to do the upload test.

**Comment by akinaru** [comment]
It seems the uri changed http://1-ipv4.testdebit.info/fichiers/1Mo.dat. It seems they provide more parameters than before and default uri doesnt work anymore https://testdebit.info/

**Comment by akinaru** [comment]
Change `1.testdebit.info` to `2.testdebit.info` or  `3.testdebit.info`. You have a list of server here https://iperf.fr/iperf-servers.php

**Comment by chandra-kantha** [comment]
Ok, Thank you, I changed the URI. Its working.
