### ISSUE TITLE
Setting TextView text inside onDownloadPacketsReceived()

### ISSUE THREAD

**Issue by poison96** [akinaru/speed-test-lib#7]
I'm having an issue where I am trying to set the text of a TextView inside the onDownloadPacketsReceived() and onUploadPacketsReceived method but the app halts as soon as it gets to setting the text. Do you have any suggestions on how to fix this?

Thanks.
```java
@Override
public void onUploadPacketsReceived(long packetSize, float transferRateBps, float transferRateOps) {
    txtStatus.setText("Speed Test Finished");
     //Reset SpeedTest for next speedtest
     resetSTT();
}
```

**Comment by akinaru** [comment]
Hi, add your run your `setText ()` in the UI thread :
```
MainActivity.this.runOnUiThread(new Runnable() {
    public void run() {
       txtStatus.setText("Speed Test Finished");
    }
});
```

**Comment by poison96** [comment]
Ahh, thank you for the help :)
